version: "3.9"

services:
  chat-assistant-bots:
    build:
      context: .
      dockerfile: Dockerfile.bots
      args:
        DATABASE_URL: ${DATABASE_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - .env
    image: chat-assistant-bots

  chat-assistant-app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
        SHOPIFY_API_SECRET: ${SHOPIFY_API_SECRET}
        SHOPIFY_APP_URL: ${SHOPIFY_APP_URL}
        SCOPES: ${SCOPES}
        DATABASE_URL: ${DATABASE_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - .env
    image: chat-assistant-app
