FROM node:18-bullseye


RUN apt-get update && \
    apt-get install -y chromium

WORKDIR /app

ARG DATABASE_URL
ARG OPENAI_API_KEY

ENV DATABASE_URL=${DATABASE_URL}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

ENV PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium'

# COPY pnpm-lock.yaml ./
COPY package.json ./
COPY pnpm-workspace.yaml ./
COPY tsconfig.base.json ./
COPY tsconfig.json ./
COPY tsup.config.ts ./

COPY apps/bots/package.json apps/bots/
COPY packages/types/package.json packages/types/
COPY packages/database/package.json packages/database/
COPY packages/services/package.json packages/services/

RUN corepack enable && pnpm install

COPY apps/bots apps/bots

COPY packages/types packages/types
RUN pnpm --filter @internal/types build

COPY packages/database packages/database
RUN pnpm --filter @internal/database build

COPY packages/services packages/services
RUN pnpm --filter @internal/services build


RUN pnpm --filter bots build


CMD ["pnpm", "--filter", "bots", "start"]