version: "3.9"

services:
  chat-assistant-bots:
    build:
      context: .
      dockerfile: Dockerfile.bots
      args:
        DATABASE_URL: ${DATABASE_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - .env
    image: chat-assistant-bots

  chat-assistant-app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        API_URL: ${API_URL}
    env_file:
      - .env
    image: chat-assistant-app
