FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

ARG DATABASE_URL
ARG OPENAI_API_KEY

ENV DATABASE_URL=$DATABASE_URL
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

COPY pnpm-lock.yaml ./
COPY package.json ./
COPY pnpm-workspace.yaml ./
COPY tsconfig.base.json ./
COPY tsconfig.json ./
COPY tsup.config.ts ./

COPY apps/bots/package.json apps/bots/
COPY packages/database/package.json packages/database/
COPY packages/services/package.json packages/services/

RUN corepack enable && pnpm install --frozen-lockfile

COPY apps/bots apps/bots

COPY packages/database packages/database
RUN pnpm --filter @internal/database build

COPY packages/services packages/services
RUN pnpm --filter @internal/services build


RUN pnpm --filter bots build

CMD ["pnpm", "--filter", "bots", "start"]