FROM node:18-bullseye

RUN apt-get update && \
    apt-get install -y chromium

WORKDIR /app

ARG DATABASE_URL
ARG OPENAI_API_KEY
ARG PORT

ENV DATABASE_URL=${DATABASE_URL}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV PUPPETEER_EXECUTABLE_PATH='/usr/bin/chromium'
ENV PORT=${PORT}

COPY pnpm-lock.yaml ./
COPY package.json ./
COPY pnpm-workspace.yaml ./
COPY tsconfig.base.json ./
COPY tsconfig.json ./
COPY tsup.config.ts ./

COPY apps/server/package.json apps/server/
COPY packages/const/package.json packages/const/
COPY packages/types/package.json packages/types/
COPY packages/database/package.json packages/database/
COPY packages/services/package.json packages/services/
COPY packages/messengers/package.json packages/messengers/

RUN corepack enable && pnpm install --frozen-lockfile

COPY apps/server apps/server

COPY packages/const packages/const
RUN pnpm --filter @internal/const build

COPY packages/types packages/types
RUN pnpm --filter @internal/types build

COPY packages/database packages/database
RUN pnpm --filter @internal/database build

COPY packages/services packages/services
RUN pnpm --filter @internal/services build

COPY packages/messengers packages/messengers
RUN pnpm --filter @internal/messengers build


RUN pnpm --filter server build

EXPOSE ${PORT}

CMD ["pnpm", "--filter", "server", "start:server"]