version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        DATABASE_URL: ${DATABASE_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        PORT: ${SERVER_PORT}
    env_file:
      - .env
    image: server

  shopify-app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
        SHOPIFY_API_SECRET: ${SHOPIFY_API_SECRET}
        SHOPIFY_APP_URL: ${SHOPIFY_APP_URL}
        SCOPES: ${SCOPES}
        DATABASE_URL: ${DATABASE_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        PORT: ${APP_PORT}
    env_file:
      - .env
    image: shopify-app
