# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ac3b631ef30cb1cb4b5ba0813aefe7d"
application_url = "https://athletics-edge-cst-written.trycloudflare.com"
embedded = true
name = "Support AI"
handle = "support-ai-5"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "nikasoul-store.myshopify.com"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [
  "https://athletics-edge-cst-written.trycloudflare.com/auth/callback",
  "https://athletics-edge-cst-written.trycloudflare.com/auth/shopify/callback",
  "https://athletics-edge-cst-written.trycloudflare.com/api/auth/callback"
]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,read_returns,write_products,write_script_tags"

[pos]
embedded = false
