import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: ["packages/services/src/index.ts"],
    outDir: "packages/services/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: false,
  },
  {
    entry: ["packages/messengers/src/index.ts"],
    outDir: "packages/messengers/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: false,
  },
  {
    entry: ["packages/database/src/index.ts"],
    outDir: "packages/database/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: false,
  },
  {
    entry: ["packages/const/src/index.ts"],
    outDir: "packages/const/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: false,
  },
  {
    entry: ["packages/types/src/index.ts"],
    outDir: "packages/types/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: false,
  },
]);
