import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: ["apps/bots/src/tg-index.ts", "apps/bots/src/wa-index.ts"],
    outDir: "apps/bots/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: false,
    minify: true,
  },
  {
    entry: ["packages/services/src/index.ts"],
    outDir: "packages/services/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: true,
  },
  {
    entry: ["packages/messengers/src/index.ts"],
    outDir: "packages/messengers/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: true,
  },
  {
    entry: ["packages/database/src/index.ts"],
    outDir: "packages/database/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: true,
  },
  {
    entry: ["packages/types/src/index.ts"],
    outDir: "packages/types/dist",
    format: ["esm"],
    splitting: false,
    sourcemap: false,
    clean: true,
    dts: true,
    minify: true,
  },
]);
