name: Deploy Shopify app to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy-shopify-app:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate Docker build args
        run: |
          echo "BUILD_ARGS=$(echo "--build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}")" >> $GITHUB_ENV

      - name: Login to Heroku
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com


      - name: Build and push to Heroku
        run: |
          docker build $BUILD_ARGS \
            -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web \
            -f Dockerfile.app .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release on Heroku
        run: |
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
