name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          provenance: false
