name: Deploy nodes to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
        shell: bash

      - name: Login to Heroku
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Build images with Docker Compose
        run: docker compose build

      - name: Tag and Push shopify-app
        run: |
          docker tag shopify-app registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Tag and Push server
        run: |
          docker tag server registry.heroku.com/${{ secrets.HEROKU_BOTS_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_BOTS_APP_NAME }}/web

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          /usr/local/bin/heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
          /usr/local/bin/heroku container:release server -a ${{ secrets.HEROKU_BOTS_APP_NAME }}
